name: json_schema3
version: 1.0.0
description: JSON Schema implementation in Dart. Fork of json_schema with sound null safety.
homepage: https://github.com/workiva/json_schema

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  collection: ^1.15.0-nullsafety.4
  http: "^0.13.4"
  logging: '>=0.9.3 <2.0.0'
  rfc_6901: ^0.1.0
  uri: '>=0.11.1 <2.0.0'

dev_dependencies:
  dependency_validator: ^3.1.2
  path: ^1.3.0
  shelf: ^1.2.0
  shelf_static: ^1.1.0
  test: ^1.9.1
  workiva_analysis_options: ^1.2.2
