name: Dart CI

on:
  push:
    branches:
      - 'master'
      - 'test_consume_*'
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sdk: [ stable, beta, dev ]
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}
      - name: Install dependencies
        run: dart pub get
      - name: Validate dependencies
        run: dart run dependency_validator
      - name: Check formatting
        run: dart format --line-length=120 --output=none --set-exit-if-changed .
        if: ${{ matrix.sdk == 'stable' }}
      - name: Analyze project source
        run: dart analyze
      - name: Check Generated Fixtures Are Up-To-Date
        run: make gen-fixtures --check
      - name: Run tests
        run: make test-with-serve-remotes